environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
install:
  - "%PYTHON%\\python.exe -m pip install opencv-python pillow mock"
  - "%PYTHON%\\python.exe -m pip install codecov coverage nose"
build: off
test_script:
  - "%PYTHON%\\Scripts\\nosetests.exe"
after_test:
  - "%PYTHON%\\Scripts\\coverage.exe run testing.py"
  - "%PYTHON%\\Scripts\\codecov.exe"
