language: python
required: sudo
python:
    "2.7"
virtualenv:
    system_site_packages: true
install:
  - sudo apt-get install python-opencv nose
script:
  - python setup.py install
  - python -m nose
after_success:
  - coverage run nosetests
  - coveralls
